# Generated by Django 5.0 on 2023-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=420)),
                ('subtitle', models.CharField(max_length=420)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=420)),
                ('published', models.DateField()),
                ('author', models.CharField(max_length=420)),
            ],
        ),
    ]
