# Generated by Django 5.0 on 2023-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ImageUrl',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
