# Generated by Django 5.0 on 2024-01-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_rename_title_review_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='review',
        ),
    ]
